server:
  port: 8080
spring:
  datasource:
    url: "jdbc:postgresql://192.168.50.93:5432/postgres"
    username: "postgres"
    password: "admin"
    driverClassName: "org.postgresql.Driver" 

logging:
  level:
    root: INFO
  file:
    name: dev.log
