server:
  port: 8081
spring:
  datasource:
    username: "postgres"
    password: "admin"
    driverClassName: "org.postgresql.Driver"
  jpa:
    show-sql: true 
  profiles:
    active: dev

logging:
  level:
    root: INFO
